name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Setup node
        uses: actions/setup-node@v2.1
        id: setup_node
      # This step prints an output (time) from the previous step's action.
      - name: Call my node
        run: npm run hello
